import {
  FinishLevel,
  MachineStatus,
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
  PrismaClient,
  PrintTechnology,
  Priority,
  UserRole,
} from "@prisma/client";
import { hash } from "bcryptjs";
import { addDays, subDays } from "date-fns";

const prisma = new PrismaClient();

async function main() {
  await prisma.orderComment.deleteMany();
  await prisma.orderTimeline.deleteMany();
  await prisma.qualityCheck.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.maintenanceRecord.deleteMany();
  await prisma.order.deleteMany();
  await prisma.session.deleteMany();
  await prisma.machine.deleteMany();
  await prisma.material.deleteMany();
  await prisma.user.deleteMany();

  const passwordHash = await hash("123456", 10);
  const now = new Date();

  const users = await Promise.all([
    prisma.user.create({
      data: {
        name: "Carolina Nogueira",
        email: "admin@printflow3d.local",
        passwordHash,
        role: UserRole.ADMIN,
        phone: "(11) 98888-0001",
        company: "PrintFlow 3D",
        address: "Av. Industrial, 900 - São Paulo/SP",
        projectType: "Gestão",
        avatarColor: "#ff7a18",
      },
    }),
    prisma.user.create({
      data: {
        name: "Bruno Matos",
        email: "supervisor@printflow3d.local",
        passwordHash,
        role: UserRole.SUPERVISOR,
        phone: "(11) 98888-0002",
        company: "PrintFlow 3D",
        address: "Av. Industrial, 900 - São Paulo/SP",
        projectType: "Operação",
        avatarColor: "#31d0aa",
      },
    }),
    prisma.user.create({
      data: {
        name: "Diego Lima",
        email: "operador@printflow3d.local",
        passwordHash,
        role: UserRole.OPERATOR,
        phone: "(11) 98888-0003",
        company: "PrintFlow 3D",
        address: "Av. Industrial, 900 - São Paulo/SP",
        projectType: "Produção",
        avatarColor: "#59b9ff",
      },
    }),
    prisma.user.create({
      data: {
        name: "Marina Costa",
        email: "cliente@printflow3d.local",
        passwordHash,
        role: UserRole.CLIENT,
        phone: "(11) 97777-1001",
        company: "Studio Vértice",
        address: "Rua das Acácias, 105 - São Paulo/SP",
        projectType: "Brindes e protótipos",
        avatarColor: "#ffc857",
      },
    }),
    prisma.user.create({
      data: {
        name: "Lucas Pereira",
        email: "compras@megatronica.com.br",
        passwordHash,
        role: UserRole.CLIENT,
        phone: "(11) 97777-1002",
        company: "Megatrônica",
        address: "Rua do Polo, 55 - Barueri/SP",
        projectType: "Peças industriais",
        avatarColor: "#ef476f",
      },
    }),
  ]);

  const [admin, supervisor, operator, clientOne, clientTwo] = users;

  const materials = await Promise.all([
    prisma.material.create({
      data: {
        name: "PLA Pro",
        category: "Filamento",
        technology: PrintTechnology.FDM,
        color: "Preto fosco",
        brand: "VoxelMax",
        lot: "PLA-2603-A",
        stockAmount: 18450,
        unit: "g",
        costPerUnit: 0.19,
        minimumStock: 3500,
        supplier: "Filamento Center",
        leadTimeDays: 2,
      },
    }),
    prisma.material.create({
      data: {
        name: "PETG Industrial",
        category: "Filamento",
        technology: PrintTechnology.FDM,
        color: "Cinza grafite",
        brand: "TechSpool",
        lot: "PETG-2603-B",
        stockAmount: 8200,
        unit: "g",
        costPerUnit: 0.24,
        minimumStock: 2500,
        supplier: "Tech Materials",
        leadTimeDays: 3,
      },
    }),
    prisma.material.create({
      data: {
        name: "Tough Resin Gray",
        category: "Resina",
        technology: PrintTechnology.RESIN,
        color: "Cinza técnico",
        brand: "ResinLab",
        lot: "RSN-2603-C",
        stockAmount: 3900,
        unit: "ml",
        costPerUnit: 0.46,
        minimumStock: 1200,
        supplier: "ResinLab",
        leadTimeDays: 4,
      },
    }),
    prisma.material.create({
      data: {
        name: "Nylon SLS Powder",
        category: "Pó",
        technology: PrintTechnology.SLS,
        color: "Natural",
        brand: "PowderTech",
        lot: "SLS-2603-D",
        stockAmount: 14200,
        unit: "g",
        costPerUnit: 0.37,
        minimumStock: 4000,
        supplier: "PowderTech",
        leadTimeDays: 5,
      },
    }),
  ]);

  const [pla, petg, resin, nylon] = materials;

  const machines = await Promise.all([
    prisma.machine.create({
      data: {
        name: "Atlas FDM 01",
        model: "Bambu X1C",
        technology: PrintTechnology.FDM,
        buildVolumeX: 25.6,
        buildVolumeY: 25.6,
        buildVolumeZ: 25.6,
        supportedMaterialNames: "PLA Pro,PETG Industrial",
        status: MachineStatus.AVAILABLE,
        responsibleOperator: operator.name,
        availableHours: 18,
        failureRate: 3.8,
        preventiveMaintenanceDays: 21,
        lastMaintenanceAt: subDays(now, 5),
        nozzleTemp: 210,
        bedTemp: 62,
        webcamUrl: "/printer-cam.svg",
        location: "Célula A",
        notes: "Equipamento principal para produção rápida e protótipos.",
      },
    }),
    prisma.machine.create({
      data: {
        name: "Atlas FDM 02",
        model: "Prusa MK4",
        technology: PrintTechnology.FDM,
        buildVolumeX: 25,
        buildVolumeY: 21,
        buildVolumeZ: 21,
        supportedMaterialNames: "PLA Pro,PETG Industrial",
        status: MachineStatus.BUSY,
        responsibleOperator: operator.name,
        availableHours: 4,
        failureRate: 5.1,
        preventiveMaintenanceDays: 28,
        lastMaintenanceAt: subDays(now, 12),
        nozzleTemp: 232,
        bedTemp: 78,
        progressPercent: 61,
        timeRemainingMinutes: 325,
        webcamUrl: "/printer-cam.svg",
        location: "Célula B",
        notes: "Linha dedicada a lotes em PETG.",
      },
    }),
    prisma.machine.create({
      data: {
        name: "Halo SLA 01",
        model: "Form 3+",
        technology: PrintTechnology.SLA,
        buildVolumeX: 14.5,
        buildVolumeY: 14.5,
        buildVolumeZ: 18.5,
        supportedMaterialNames: "Tough Resin Gray",
        status: MachineStatus.MAINTENANCE,
        responsibleOperator: supervisor.name,
        availableHours: 0,
        failureRate: 6.4,
        preventiveMaintenanceDays: 15,
        lastMaintenanceAt: subDays(now, 18),
        webcamUrl: "/printer-cam.svg",
        location: "Célula Resina",
        notes: "Em manutenção preventiva para limpeza do tanque.",
      },
    }),
    prisma.machine.create({
      data: {
        name: "ResinCore R1",
        model: "Uniformation GKTwo",
        technology: PrintTechnology.RESIN,
        buildVolumeX: 22.8,
        buildVolumeY: 12.8,
        buildVolumeZ: 24.5,
        supportedMaterialNames: "Tough Resin Gray",
        status: MachineStatus.BUSY,
        responsibleOperator: operator.name,
        availableHours: 2,
        failureRate: 4.5,
        preventiveMaintenanceDays: 18,
        lastMaintenanceAt: subDays(now, 8),
        nozzleTemp: 31,
        bedTemp: 29,
        progressPercent: 48,
        timeRemainingMinutes: 154,
        webcamUrl: "/printer-cam.svg",
        location: "Célula Resina",
        notes: "Monitorada por webcam e checklist UV.",
      },
    }),
  ]);

  const [atlasOne, atlasTwo, haloSla, resinCore] = machines;

  await prisma.maintenanceRecord.createMany({
    data: [
      {
        machineId: atlasOne.id,
        type: "Preventiva",
        summary: "Lubrificação de eixos e troca de bico 0.4 mm.",
        status: "Concluída",
        scheduledAt: subDays(now, 5),
        completedAt: subDays(now, 5),
        cost: 78,
      },
      {
        machineId: haloSla.id,
        type: "Preventiva",
        summary: "Substituição de tanque e recalibração do laser.",
        status: "Em andamento",
        scheduledAt: addDays(now, 1),
        cost: 180,
      },
      {
        machineId: resinCore.id,
        type: "Corretiva",
        summary: "Ajuste do sistema de nivelamento da plataforma.",
        status: "Agendada",
        scheduledAt: addDays(now, 4),
        cost: 95,
      },
    ],
  });

  const sampleFile = {
    fileName: "sample-gear.obj",
    fileUrl: "/uploads/sample-gear.obj",
    fileFormat: "obj",
  };

  const orders = [
    {
      orderNumber: "PF-20260327-001",
      title: "Suporte articulado para webcam",
      type: "Protótipo funcional",
      description: "Peça para fixação de câmera em bancada de gravação.",
      fileSizeKb: 148,
      technology: PrintTechnology.FDM,
      quantity: 4,
      color: "Preto fosco",
      finishLevel: FinishLevel.PREMIUM,
      urgencyMultiplier: 1.12,
      priority: Priority.HIGH,
      status: OrderStatus.WAITING_APPROVAL,
      paymentStatus: PaymentStatus.PENDING,
      boundingBoxX: 9.8,
      boundingBoxY: 6.5,
      boundingBoxZ: 4.2,
      estimatedVolumeCm3: 56.2,
      estimatedSupportCm3: 8.1,
      estimatedHours: 6.4,
      estimatedWeightGrams: 156,
      failureRisk: 32,
      needsManualReview: false,
      materialCost: 29.64,
      machineCost: 115.2,
      energyCost: 12.48,
      laborCost: 51.2,
      finishingCost: 28.8,
      packagingCost: 14.4,
      subtotal: 251.72,
      marginPercent: 14,
      totalPrice: 286.96,
      realCost: 223.41,
      grossMargin: 63.55,
      dueDate: addDays(now, 4),
      materialName: pla.name,
      materialId: pla.id,
      customerId: clientOne.id,
      comments: [
        { authorId: clientOne.id, message: "Preciso validar se a articulação aguenta uso diário em estúdio." },
        {
          authorId: supervisor.id,
          internal: true,
          message: "Geometria está limpa, sem necessidade de correção manual.",
        },
      ],
      timeline: [
        {
          actorId: clientOne.id,
          label: "Pedido recebido",
          details: "Arquivo OBJ enviado no portal do cliente.",
          statusSnapshot: OrderStatus.RECEIVED,
          createdAt: subDays(now, 1),
        },
        {
          actorId: supervisor.id,
          label: "Análise automática concluída",
          details: "Orçamento calculado sem necessidade de revisão manual.",
          statusSnapshot: OrderStatus.WAITING_APPROVAL,
        },
      ],
    },
    {
      orderNumber: "PF-20260327-002",
      title: "Lote de conectores PETG",
      type: "Produção seriada",
      description: "Peças para gabinete técnico com exigência de resistência térmica.",
      fileSizeKb: 222,
      technology: PrintTechnology.FDM,
      quantity: 18,
      color: "Cinza grafite",
      finishLevel: FinishLevel.STANDARD,
      urgencyMultiplier: 1.24,
      priority: Priority.URGENT,
      status: OrderStatus.PRINTING,
      paymentStatus: PaymentStatus.PAID,
      boundingBoxX: 7.4,
      boundingBoxY: 5.3,
      boundingBoxZ: 4.1,
      estimatedVolumeCm3: 93.8,
      estimatedSupportCm3: 9.2,
      estimatedHours: 22.5,
      estimatedWeightGrams: 1240,
      failureRisk: 44,
      needsManualReview: false,
      materialCost: 297.6,
      machineCost: 405,
      energyCost: 43.88,
      laborCost: 213.84,
      finishingCost: 130.14,
      packagingCost: 36.8,
      subtotal: 1399.73,
      marginPercent: 18,
      totalPrice: 1651.68,
      realCost: 1187.24,
      grossMargin: 464.44,
      dueDate: addDays(now, 2),
      approvedByCustomerAt: subDays(now, 2),
      paidAt: subDays(now, 2),
      materialName: petg.name,
      materialId: petg.id,
      customerId: clientTwo.id,
      assignedMachineId: atlasTwo.id,
      assignedOperatorId: operator.id,
      queuePosition: 1,
      payment: {
        method: PaymentMethod.CARD,
        status: PaymentStatus.PAID,
        amount: 1651.68,
        paidAt: subDays(now, 2),
        gateway: "Asaas Demo",
        referenceCode: "PAY-CARD-2201",
      },
      comments: [
        { authorId: clientTwo.id, message: "Confirmado. Podemos seguir com a produção assim que o pagamento cair." },
        { authorId: operator.id, internal: true, message: "Impressão distribuída em 3 placas, 61% concluída." },
      ],
      timeline: [
        {
          actorId: clientTwo.id,
          label: "Pedido aprovado",
          details: "Cliente aprovou orçamento e confirmou urgência.",
          statusSnapshot: OrderStatus.WAITING_PAYMENT,
          createdAt: subDays(now, 2),
        },
        {
          actorId: admin.id,
          label: "Pagamento aprovado",
          details: "Cartão validado e pedido liberado para fila.",
          statusSnapshot: OrderStatus.QUEUED,
          createdAt: subDays(now, 2),
        },
        {
          actorId: operator.id,
          label: "Produção iniciada",
          details: "Lote encaminhado para Atlas FDM 02.",
          statusSnapshot: OrderStatus.PRINTING,
          createdAt: subDays(now, 1),
        },
      ],
    },
    {
      orderNumber: "PF-20260327-003",
      title: "Miniatura para validação visual",
      type: "Modelo estético",
      description: "Boneco conceitual com pós-processamento e cura UV.",
      fileSizeKb: 312,
      technology: PrintTechnology.RESIN,
      quantity: 2,
      color: "Cinza técnico",
      finishLevel: FinishLevel.PAINTED,
      urgencyMultiplier: 1,
      priority: Priority.MEDIUM,
      status: OrderStatus.POST_PROCESSING,
      paymentStatus: PaymentStatus.PAID,
      boundingBoxX: 11.8,
      boundingBoxY: 8.4,
      boundingBoxZ: 15.6,
      estimatedVolumeCm3: 102.4,
      estimatedSupportCm3: 18.7,
      estimatedHours: 9.2,
      estimatedWeightGrams: 229.4,
      failureRisk: 67,
      needsManualReview: true,
      materialCost: 105.52,
      machineCost: 165.6,
      energyCost: 17.94,
      laborCost: 29.04,
      finishingCost: 31.68,
      packagingCost: 11.2,
      subtotal: 360.98,
      marginPercent: 22,
      totalPrice: 440.4,
      realCost: 333.5,
      grossMargin: 106.9,
      dueDate: addDays(now, 3),
      approvedByCustomerAt: subDays(now, 4),
      paidAt: subDays(now, 3),
      materialName: resin.name,
      materialId: resin.id,
      customerId: clientOne.id,
      assignedMachineId: resinCore.id,
      assignedOperatorId: operator.id,
      queuePosition: 2,
      payment: {
        method: PaymentMethod.PIX,
        status: PaymentStatus.PAID,
        amount: 440.4,
        paidAt: subDays(now, 3),
        gateway: "Pix interno",
        referenceCode: "PIX-883401",
      },
      comments: [{ authorId: operator.id, internal: true, message: "Peças já lavadas, cura UV concluída." }],
      timeline: [
        {
          actorId: supervisor.id,
          label: "Revisão manual",
          details: "Arquivo marcado para revisão por volume alto de suportes.",
          statusSnapshot: OrderStatus.ANALYSIS,
          createdAt: subDays(now, 5),
        },
        {
          actorId: operator.id,
          label: "Pós-processamento iniciado",
          details: "Lavagem e cura UV concluídas.",
          statusSnapshot: OrderStatus.POST_PROCESSING,
          createdAt: subDays(now, 1),
        },
      ],
    },
    {
      orderNumber: "PF-20260327-004",
      title: "Caixa eletrônica customizada",
      type: "Peça funcional",
      description: "Carcaça com acabamento premium e inspeção dimensional.",
      fileSizeKb: 190,
      technology: PrintTechnology.FDM,
      quantity: 6,
      color: "Preto fosco",
      finishLevel: FinishLevel.PREMIUM,
      urgencyMultiplier: 1,
      priority: Priority.HIGH,
      status: OrderStatus.READY_TO_SHIP,
      paymentStatus: PaymentStatus.PAID,
      boundingBoxX: 18.5,
      boundingBoxY: 12.2,
      boundingBoxZ: 7.6,
      estimatedVolumeCm3: 134.5,
      estimatedSupportCm3: 14.2,
      estimatedHours: 14.8,
      estimatedWeightGrams: 470.1,
      failureRisk: 39,
      needsManualReview: false,
      materialCost: 89.32,
      machineCost: 266.4,
      energyCost: 28.86,
      laborCost: 77.88,
      finishingCost: 53.1,
      packagingCost: 17.6,
      subtotal: 533.16,
      marginPercent: 24,
      totalPrice: 661.12,
      realCost: 504.8,
      grossMargin: 156.32,
      dueDate: addDays(now, 1),
      approvedByCustomerAt: subDays(now, 8),
      paidAt: subDays(now, 8),
      invoiceNumber: "NF-2026-0314",
      materialName: pla.name,
      materialId: pla.id,
      customerId: clientTwo.id,
      assignedMachineId: atlasOne.id,
      assignedOperatorId: operator.id,
      payment: {
        method: PaymentMethod.BOLETO,
        status: PaymentStatus.PAID,
        amount: 661.12,
        paidAt: subDays(now, 7),
        gateway: "Banco parceiro",
        referenceCode: "BOL-10298",
      },
      qualityCheck: {
        inspectorId: supervisor.id,
        dimensionsOk: true,
        finishOk: true,
        deformationFree: true,
        colorOk: true,
        strengthOk: true,
        packagingOk: true,
        approved: true,
        notes: "Peça aprovada e embalada com espuma técnica.",
      },
      timeline: [
        {
          actorId: operator.id,
          label: "Produção finalizada",
          details: "Peças concluídas e encaminhadas para acabamento.",
          statusSnapshot: OrderStatus.POST_PROCESSING,
          createdAt: subDays(now, 2),
        },
        {
          actorId: supervisor.id,
          label: "Qualidade aprovada",
          details: "Checklist completo sem não conformidades.",
          statusSnapshot: OrderStatus.READY_TO_SHIP,
          createdAt: subDays(now, 1),
        },
      ],
    },
    {
      orderNumber: "PF-20260327-005",
      title: "Garra mecânica articulada",
      type: "Protótipo de validação",
      description: "Conjunto que falhou na primeira impressão e entrou em retrabalho.",
      fileSizeKb: 260,
      technology: PrintTechnology.SLS,
      quantity: 1,
      color: "Natural",
      finishLevel: FinishLevel.STANDARD,
      urgencyMultiplier: 1,
      priority: Priority.MEDIUM,
      status: OrderStatus.FAILED_REWORK,
      paymentStatus: PaymentStatus.PARTIAL,
      boundingBoxX: 16.2,
      boundingBoxY: 9.4,
      boundingBoxZ: 12.1,
      estimatedVolumeCm3: 88.6,
      estimatedSupportCm3: 6.1,
      estimatedHours: 7.8,
      estimatedWeightGrams: 92.8,
      failureRisk: 74,
      needsManualReview: true,
      materialCost: 34.34,
      machineCost: 140.4,
      energyCost: 15.21,
      laborCost: 11.88,
      finishingCost: 8.1,
      packagingCost: 9.6,
      subtotal: 219.53,
      marginPercent: 20,
      totalPrice: 263.44,
      realCost: 241.1,
      grossMargin: 22.34,
      dueDate: addDays(now, 6),
      approvedByCustomerAt: subDays(now, 2),
      paidAt: subDays(now, 2),
      materialName: nylon.name,
      materialId: nylon.id,
      customerId: clientTwo.id,
      payment: {
        method: PaymentMethod.TRANSFER,
        status: PaymentStatus.PARTIAL,
        amount: 131.72,
        paidAt: subDays(now, 2),
        gateway: "Banco parceiro",
        referenceCode: "TRF-2204",
      },
      comments: [
        { authorId: operator.id, internal: true, message: "Detectada deformação em base de apoio. Pedido voltou para retrabalho." },
      ],
      timeline: [
        {
          actorId: operator.id,
          label: "Falha detectada",
          details: "Warping durante resfriamento. Retrabalho autorizado.",
          statusSnapshot: OrderStatus.FAILED_REWORK,
          createdAt: subDays(now, 1),
        },
      ],
    },
    {
      orderNumber: "PF-20260327-006",
      title: "Keycaps promocionais",
      type: "Brinde corporativo",
      description: "Pedido finalizado e entregue, pronto para reimpressão com um clique.",
      fileSizeKb: 130,
      technology: PrintTechnology.FDM,
      quantity: 24,
      color: "Branco",
      finishLevel: FinishLevel.STANDARD,
      urgencyMultiplier: 1,
      priority: Priority.LOW,
      status: OrderStatus.COMPLETED,
      paymentStatus: PaymentStatus.PAID,
      boundingBoxX: 1.8,
      boundingBoxY: 1.8,
      boundingBoxZ: 1.4,
      estimatedVolumeCm3: 18.6,
      estimatedSupportCm3: 1.4,
      estimatedHours: 5.5,
      estimatedWeightGrams: 82.3,
      failureRisk: 18,
      needsManualReview: false,
      materialCost: 15.64,
      machineCost: 99,
      energyCost: 10.72,
      laborCost: 285.12,
      finishingCost: 173.88,
      packagingCost: 46.4,
      subtotal: 630.76,
      marginPercent: 16,
      totalPrice: 731.68,
      realCost: 579.2,
      grossMargin: 152.48,
      dueDate: subDays(now, 12),
      approvedByCustomerAt: subDays(now, 18),
      paidAt: subDays(now, 18),
      shippedAt: subDays(now, 13),
      deliveredAt: subDays(now, 12),
      shippingCarrier: "Motoboy urbano",
      trackingCode: "ENT-5567",
      invoiceNumber: "NF-2026-0262",
      materialName: pla.name,
      materialId: pla.id,
      customerId: clientOne.id,
      payment: {
        method: PaymentMethod.PIX,
        status: PaymentStatus.PAID,
        amount: 731.68,
        paidAt: subDays(now, 18),
        gateway: "Pix interno",
        referenceCode: "PIX-73168",
      },
      timeline: [
        {
          actorId: admin.id,
          label: "Pedido expedido",
          details: "Etiqueta gerada e entrega urbana agendada.",
          statusSnapshot: OrderStatus.SHIPPED,
          createdAt: subDays(now, 13),
        },
        {
          actorId: clientOne.id,
          label: "Entrega confirmada",
          details: "Cliente confirmou recebimento e aprovou qualidade.",
          statusSnapshot: OrderStatus.COMPLETED,
          createdAt: subDays(now, 12),
        },
      ],
    },
  ];

  for (const order of orders) {
    const { payment, qualityCheck, comments, timeline, ...data } = order;
    await prisma.order.create({
      data: {
        ...sampleFile,
        ...data,
        payments: payment ? { create: payment } : undefined,
        comments: comments?.length ? { create: comments } : undefined,
        qualityChecks: qualityCheck ? { create: qualityCheck } : undefined,
        timeline: timeline?.length ? { create: timeline } : undefined,
      },
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
